# Build stage
FROM node:16.13 AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Run stage
FROM node:16.13
WORKDIR /usr/src/app
COPY --from=build /usr/src/app .
EXPOSE 3001
CMD ["npm", "run", "dev"]
