# Generated by Django 4.2.7 on 2023-11-16 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_state',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Player'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=15),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
