# Generated by Django 4.2.8 on 2023-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball_velocity_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_velocity_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='pad1_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='pad2_x',
            field=models.FloatField(default=0),
        ),
    ]
