# Generated by Django 4.2.9 on 2024-01-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_ball_velocity_x_game_ball_velocity_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_score',
            field=models.IntegerField(default=5),
        ),
    ]
