# Generated by Django 4.2.9 on 2024-01-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pad1_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='pad2_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player_turn',
            field=models.IntegerField(default=1),
        ),
    ]
