# Generated by Django 4.2.9 on 2024-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='pad_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='pad_width',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_turn',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Player 1'), (2, 'Player 2')], default=1),
        ),
    ]
