# Generated by Django 4.2.9 on 2024-02-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_game_height_alter_game_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='height',
        ),
        migrations.RemoveField(
            model_name='game',
            name='width',
        ),
        migrations.AddField(
            model_name='game',
            name='ball_width',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='win_height',
            field=models.FloatField(default=563),
        ),
        migrations.AddField(
            model_name='game',
            name='win_width',
            field=models.FloatField(default=426),
        ),
        migrations.AlterField(
            model_name='game',
            name='ball_velocity_y',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='ball_x',
            field=models.FloatField(default=213),
        ),
        migrations.AlterField(
            model_name='game',
            name='ball_y',
            field=models.FloatField(default=281.5),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad1_x',
            field=models.FloatField(default=213),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad1_y',
            field=models.FloatField(default=513),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad2_x',
            field=models.FloatField(default=213),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad2_y',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad_height',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad_width',
            field=models.FloatField(default=100),
        ),
    ]
