# Generated by Django 4.2.9 on 2024-02-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_game_height_remove_game_width_game_ball_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball_moving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_turn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
