# Generated by Django 4.2.9 on 2024-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_ball_moving_game_paused_alter_game_player_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ball_velocity_y',
            field=models.FloatField(default=-5),
        ),
    ]
