# Generated by Django 4.2.9 on 2024-02-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_game_ball_velocity_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
