# Generated by Django 4.2.9 on 2024-02-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='group_name',
        ),
    ]
