# Generated by Django 4.2.9 on 2024-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_remove_game_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ball_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='ball_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad1_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad1_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad2_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='pad2_y',
            field=models.FloatField(default=0),
        ),
    ]
