# Generated by Django 4.2.9 on 2024-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_alter_game_ball_x_alter_game_ball_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('waiting', 'Waiting for Player'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='empty', max_length=15),
        ),
    ]
