# Generated by Django 4.2.9 on 2024-02-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_rename_order_match_match_order_match_round_number'),
        ('games', '0021_game_tournament_delete_matchmakingqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_games', to='tournaments.tournament'),
        ),
    ]
