# Generated by Django 4.2.9 on 2024-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_alter_game_ball_velocity_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ball_velocity_y',
            field=models.FloatField(default=-10),
        ),
    ]
