global:
  resolve_timeout: 5m
  smtp_require_tls: true
route:
  group_by: ["instance", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: "email-me"
  routes:
    - match:
        alertname: server_down

receivers:
  - name: "email-me"
    email_configs:
      - to: "bonvin.quentin@gmail.com"
        from: "bonvin.quentin@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "bonvin.quentin@gmail.com"
        auth_identity: "bonvin.quentin@gmail.com"
        auth_password: "rxht mbpj nbvt kvzf"
        send_resolved: true
