global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - backend:8000
    #relabel_configs:
     # - source_labels: [__address__]
      #  target_label: instance