global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "./alert_rules.yml"

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - backend:8000
  - job_name: 'nginx'
    static_configs:
      - targets: [ 'nginx-prometheus-exporter:9113' ]
    #relabel_configs:
     # - source_labels: [__address__]
      #  target_label: instance