# Generated by Django 4.2.7 on 2023-11-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_winner_alter_tournament_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchmakingQueue',
        ),
    ]
