# Generated by Django 4.2.7 on 2023-11-14 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0003_match_matchmakingqueue_playerprofile_round_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='TournamentMatch',
        ),
    ]
