# Generated by Django 4.2.9 on 2024-02-14 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_alter_game_ball_x_alter_game_ball_y_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0008_remove_tournament_tournament_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournaments', to='games.game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Tournament', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
