# Generated by Django 4.2.9 on 2024-02-14 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0012_alter_tournament_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Tournament', max_length=15),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
