# Generated by Django 4.2.9 on 2024-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_rename_order_match_match_order_match_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Tournament', max_length=10),
        ),
    ]
