{
 "title": "Nginx",
 "description": "Grafana Dashboard for Nginx Web Server.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(system_uptime, instance)"
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Nginx Requests Status Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Response 200 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 200 response by nginx server",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "transcendence_django_http_responses_total_by_status_view_method_total{view!=\"prometheus-django-metrics\", status=~\"20.\"}",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Total Response 404 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 404 response from nginx server",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(transcendence_django_http_responses_total_by_status_view_method_total{status=\"404\"})",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Response 3XX",
   "type": "timeseries",
   "description": "Requests with 3XX Status Code",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time(transcendence_django_http_responses_total_by_status_view_method_total{status=~\"30.\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response 5XX",
   "type": "timeseries",
   "description": "Requests with 5XX Status Code",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time(transcendence_django_http_responses_total_by_status_view_method_total{status=~\"50.\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Request 503 Resonse",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(promhttp_metric_handler_requests_total{status=\"503\"})",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Nginx Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nginx Writing",
   "type": "stat",
   "description": "The current number of connections from clients where nginx is writing a response back to the client.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nginx_connections_writing", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "nginx_reading",
   "type": "stat",
   "description": "The current number of (accepted) connections from clients where nginx is reading the request. Measured at the time the status module was queried.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "Nginx Writing",
   "type": "stat",
   "description": "The current number of connections from clients where nginx is writing a response back to the client.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nginx_connections_writing", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "Nginx Active Connections[accepted]",
   "type": "bargauge",
   "description": "The current number of active (accepted) connections from clients. Includes all connections with the statuses Idle / Waiting, Reading, and Writing.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{instance }}" }
   ]
  },
  {
   "title": "Nginx Waiting Connections",
   "type": "stat",
   "description": "The current number of connections from clients that are in the Idle / Waiting state.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "{{ instance}}" }
   ]
  },
  {
   "title": "Nginx Connections Accepted",
   "type": "timeseries",
   "description": "The total number of accepted connections from clients since the nginx master process started. Note that reloading configurations or restarting worker processes will not reset this metric. If you terminate and restart the master process, you will reset the metric.\n\n",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_accepted", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Handled Request",
   "type": "timeseries",
   "description": "The total number of handled connections from clients since the nginx master process started. This will be lower than accepted only in cases where a connection is dropped before it is handled.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_handled", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}