# Generated by Django 4.2.7 on 2023-11-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/default_avatar.png', upload_to='profiles/avatars/'),
        ),
    ]
