# Generated by Django 4.2.7 on 2023-11-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
