# Generated by Django 4.2.8 on 2023-12-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_bio_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.IntegerField(default=0)),
                ('players', models.ManyToManyField(related_name='tournament_history_played', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_history_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
