# Generated by Django 4.2.7 on 2023-11-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231115_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
