# Generated by Django 4.2.7 on 2023-11-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
