# Generated by Django 4.2.9 on 2024-01-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_oauth_user',
            field=models.BooleanField(default=False),
        ),
    ]
