# Generated by Django 4.2.9 on 2024-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_otp_customuser_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twofa',
            field=models.BooleanField(default=False),
        ),
    ]
