# Generated by Django 4.2.9 on 2024-02-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_twofa'),
        ('users', '0010_alter_customuser_email'),
    ]

    operations = [
    ]
