# Generated by Django 4.2.9 on 2024-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20240216_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True),
        ),
    ]
