# Generated by Django 4.2.7 on 2023-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
