# Generated by Django 4.2.9 on 2024-02-22 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='players',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_history_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_history_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_history_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
