# Generated by Django 4.2.7 on 2023-11-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_friends_customuser_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='online',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in-game', 'In-Game'), ('queuing', 'Queuing')], default='offline', max_length=10),
        ),
    ]
