# Generated by Django 4.2.9 on 2024-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_gamehistory_players_gamehistory_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='idft',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
