# Generated by Django 4.2.9 on 2024-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_idft_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idft',
            field=models.IntegerField(default=0),
        ),
    ]
